# SPDX-FileCopyrightText: 2023 Phu Hung Nguyen <phuhnguyen@outlook.com>
# SPDX-License-Identifier: CC0-1.0

[build-system]
requires = ["setuptools>=50"]
build-backend = "setuptools.build_meta"

[project]
name = "mdit-py-i18n"
version = "0.2.1"
description = "Markdown i18n and l10n using markdown-it-py"
authors = [
    { name = "Phu Hung Nguyen", email = "phuhnguyen@outlook.com" }
]
# This is a legacy way to specifiy the license
license = {text = "LGPL-2.1-or-later"}
# The below is be the modern replacement but not supported by setuptools with Python 3.8
# See https://setuptools.pypa.io/en/stable/userguide/license_migration.html
#license = "LGPL-2.1-or-later"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Internationalization",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3"
]

# The KDE Scripty host runs an ancient Python 3.8. Check if this has changed,
# before raising the minimum required Python version here!
requires-python = ">=3.8"

dependencies = [
    "markdown-it-py[plugins]>=3.0.0",
    "Pygments>=2.16.1",
]

[project.urls]
Repository = "https://invent.kde.org/sdk/mdit-py-i18n.git"

[tool.isort]
profile = "black"

[tool.tox]
requires = ["tox>=4.19"]
envlist = ["sort-imports"]

[tool.tox.env.tests]
description = "Runs pytest"
deps = ["pytest"]
commands = [["pytest"]]

[tool.tox.env.lint]
description = "runs flake8"
skip_install = true
deps = ["flake8==7.3.0"]
commands = [["flake8", "."]]

[tool.tox.env.check-imports]
description = "runs isort --check"
skip_install = true
deps = ["isort==7.0.0"]
commands = [["isort", "--check", "."]]

[tool.tox.env.sort-imports]
description = "runs isort"
skip_install = true
deps = ["isort==7.0.0"]
commands = [["isort", "."]]

[tool.tox.env.format]
description = "runs black"
skip_install = true
deps = ["black==25.12.0"]
commands = [["black", "."]]
